### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by sephii** [eventable/vobject#1]
Installation fails on Python 3:

```
$ pip install vobject
Collecting vobject
  Downloading vobject-0.6.6.tar.gz (53kB)
    100% |████████████████████████████████| 57kB 3.0MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rcah3vyp/vobject/setup.py", line 31, in <module>
        from ez_setup import use_setuptools
      File "/tmp/pip-build-rcah3vyp/vobject/ez_setup/__init__.py", line 94
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
```

**Comment by skarim** [comment]
Python 3 support will be in the upcoming `0.9.0` release
See #4 for details
