### ISSUE TITLE
version 0.8.2 fails test suite

### ISSUE THREAD

**Issue by lfam** [eventable/vobject#14]
Hi,

I've been working on a package for GNU Guix that depends on vobject. When 0.8.1c was removed from PyPi, I tried updating to 0.8.2. Unfortunately, this version of vobject fails its test suite.

I'm building with python-2.7.10, pyicu-1.8, and dateutil-2.4.2.

I've included the failing portion of the build log below. Please let me know if I can provide more information.

```
phase `build' succeeded after 0.1 seconds
starting phase `check'
running "python setup.py" with command "test" and parameters ()
running test
running egg_info
writing requirements to vobject.egg-info/requires.txt
writing vobject.egg-info/PKG-INFO
writing top-level names to vobject.egg-info/top_level.txt
writing dependency_links to vobject.egg-info/dependency_links.txt
writing entry points to vobject.egg-info/entry_points.txt
reading manifest file 'vobject.egg-info/SOURCES.txt'
writing manifest file 'vobject.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    Topic :: Text Processing""".strip().splitlines()
  File "/gnu/store/plpfbrhpfidc2nsnclm3d4zc5d1815a0-python-2.7.10/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/gnu/store/plpfbrhpfidc2nsnclm3d4zc5d1815a0-python-2.7.10/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/gnu/store/plpfbrhpfidc2nsnclm3d4zc5d1815a0-python-2.7.10/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/gnu/store/fr88c7i5vwdzdnsjlmf9nxhmsmfbw4pr-python2-setuptools-18.3.1/lib/python2.7/site-packages/setuptools-18.3.1-py2.7.egg/setuptools/command/test.py", line 142, in run
  File "/gnu/store/fr88c7i5vwdzdnsjlmf9nxhmsmfbw4pr-python2-setuptools-18.3.1/lib/python2.7/site-packages/setuptools-18.3.1-py2.7.egg/setuptools/command/test.py", line 122, in with_project_on_sys_path
  File "/gnu/store/fr88c7i5vwdzdnsjlmf9nxhmsmfbw4pr-python2-setuptools-18.3.1/lib/python2.7/site-packages/setuptools-18.3.1-py2.7.egg/setuptools/command/test.py", line 163, in run_tests
  File "/gnu/store/plpfbrhpfidc2nsnclm3d4zc5d1815a0-python-2.7.10/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/gnu/store/plpfbrhpfidc2nsnclm3d4zc5d1815a0-python-2.7.10/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/gnu/store/plpfbrhpfidc2nsnclm3d4zc5d1815a0-python-2.7.10/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/gnu/store/plpfbrhpfidc2nsnclm3d4zc5d1815a0-python-2.7.10/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/gnu/store/plpfbrhpfidc2nsnclm3d4zc5d1815a0-python-2.7.10/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: No module named test_vobject
phase `check' failed after 0.2 seconds
builder for `/gnu/store/za9r10l4qakjk7jhykl8fb80863s1smf-python2-vobject-0.8.2.drv' failed with exit code 1
@ build-failed /gnu/store/za9r10l4qakjk7jhykl8fb80863s1smf-python2-vobject-0.8.2.drv - 1 builder for `/gnu/store/za9r10l4qakjk7jhykl8fb80863s1smf-python2-vobject-0.8.2.drv' failed with exit code 1
guix build: error: build failed: build of `/gnu/store/za9r10l4qakjk7jhykl8fb80863s1smf-python2-vobject-0.8.2.drv' failed
```

**Comment by lfam** [comment]
I packaged dateutil-2.4.0, and vobject-0.9.0 works fine. So, feel free to close this bug if you like.
