### ISSUE TITLE
vobject fails to parse this vcard

### ISSUE THREAD

**Issue by Volker-Weissmann** [eventable/vobject#160]
This code:
```
import vobject
el = """BEGIN:VCARD
VERSION:2.1
N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;=57=6F=6C=6C=6B=6E=C3=A4=75=65=6C=20=53=6F=63=6B=65=6E=62=61=72=74=20=
=45=50;;;
FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=57=6F=6C=6C=6B=6E=C3=A4=75=65=6C=20=53=6F=63=6B=65=6E=62=61=72=74=20=
=45=50
TEL;CELL:+123456
TEL;CELL:+123456
END:VCARD"""
print(vobject.readOne(el))
```

fails with the message
```
Traceback (most recent call last):
  File "/path/to/script.py", line 32, in <module>
    print(vobject.readOne(el))
  File "/home/volker/.local/lib/python3.9/site-packages/vobject/base.py", line 1155, in readOne
    return next(readComponents(stream, validate, transform, ignoreUnreadable,
  File "/home/volker/.local/lib/python3.9/site-packages/vobject/base.py", line 1101, in readComponents
    vline = textLineToContentLine(line, n)
  File "/home/volker/.local/lib/python3.9/site-packages/vobject/base.py", line 925, in textLineToContentLine
    return ContentLine(*parseLine(text, n), **{'encoded': True,
  File "/home/volker/.local/lib/python3.9/site-packages/vobject/base.py", line 813, in parseLine
    raise ParseError("Failed to parse line: {0!s}".format(line), lineNumber)
vobject.base.ParseError: At line 7: Failed to parse line: =45=50;;;
```

**Comment by svilendobrev** [comment]
instead of waiting for the library to be fixed...
Seems most/android phone exporters split long lines (>115) this way - ending on '=' then next line starts with '='. Most non-ascii names hit this limit easily.

newvcardtext = vcardtext.replace( '=\n=', '=') 
works fine joining them back; use on single vcard or over whole vcf file/text, before parsing with vobject.

**Comment by Volker-Weissmann** [comment]
Thank you, this works.

**Comment by elig0n** [comment]
You must allow QP decoding since the parser knows how to decode it:

``` python
print(vobject.readOne(el, allowQP=True))
```

**Comment by Volker-Weissmann** [comment]
> print(vobject.readOne(el, allowQP=True))

This also works.
