### ISSUE TITLE
AttributeError: 'Address' object has no attribute 'replace'

### ISSUE THREAD

**Issue by miynat** [eventable/vobject#179]
When I try to add an address to a vCard with vobject.vcard.Address() object, I'm getting 

> AttributeError: 'Address' object has no attribute 'replace'

error.

Even the sample code in [vobject/test_files/more_tests.txt ](https://github.com/eventable/vobject/blob/master/test_files/more_tests.txt) file is throwing the same error:

```
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vobject
>>> card = vobject.vCard()
>>> card.add('fn').value = u'Hello\u1234 World!'
>>> card.add('addr').value = vobject.vcard.Address(u'5\u1234 Nowhere, Apt 1', 'Berkeley', 'CA', '94704', 'USA')
>>> card
<VCARD| [<ADDR{}5ሴ Nowhere, Apt 1
Berkeley, CA 94704
USA>, <FN{}Helloሴ World!>]>
>>> card.serialize()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/selcuk/flask-google-auth/env/lib/python3.9/site-packages/vobject/base.py", line 254, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/home/selcuk/flask-google-auth/env/lib/python3.9/site-packages/vobject/behavior.py", line 166, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/home/selcuk/flask-google-auth/env/lib/python3.9/site-packages/vobject/base.py", line 1007, in defaultSerialize
    child.serialize(outbuf, lineLength, validate=False)
  File "/home/selcuk/flask-google-auth/env/lib/python3.9/site-packages/vobject/base.py", line 254, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/home/selcuk/flask-google-auth/env/lib/python3.9/site-packages/vobject/behavior.py", line 166, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/home/selcuk/flask-google-auth/env/lib/python3.9/site-packages/vobject/base.py", line 1015, in defaultSerialize
    obj.behavior.encode(obj)
  File "/home/selcuk/flask-google-auth/env/lib/python3.9/site-packages/vobject/vcard.py", line 161, in encode
    line.value = backslashEscape(line.value)
  File "/home/selcuk/flask-google-auth/env/lib/python3.9/site-packages/vobject/base.py", line 1219, in backslashEscape
    s = s.replace("\\", "\\\\").replace(";", "\;").replace(",", "\,")
AttributeError: 'Address' object has no attribute 'replace'
```

What could be the reason for that, and how can I fix that?

Regards,

**Comment by miynat** [comment]
Sorry, my bad. I made a typo, and wrote `card.add('addr').value` instead of `card.add('adr').value`
