### ISSUE TITLE
Serializing iCalendar throws NonExistentTimeError when using pytz timezones

### ISSUE THREAD

**Issue by medmunds** [eventable/vobject#32]
Are pytz timezones meant to be supported for event times when generating an iCalendar?
(This is *probably* the same as the original issue reported in #18.)

The code below throws a `pytz.NonExistentTimeError` in the serialize call, while attempting to automatically generate the VTIMEZONE block for TZID=America/Los_Angeles:

```python
from datetime import datetime
import vobject
import pytz

ical = vobject.iCalendar()
vevent = ical.add('vevent')
vevent.add('dtstart').value = datetime(
    2016, 5, 26, 14, 30, tzinfo=pytz.timezone("America/Los_Angeles"))
ical.serialize()  # NonExistentTimeError: 2000-04-02 02:00:00
```

If not, would pytz support be a reasonable addition to propose? (It seems to be Django's preferred tz source.) Or is there a strong preference for dateutil timezones with vobject?

Python 2.7.11; vobject==0.9.2; python-dateutil==2.5.3; six==1.10.0; pytz==2016.4
```
Traceback (most recent call last):
  File "...lib/python2.7/site-packages/vobject/base.py", line 254, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "...lib/python2.7/site-packages/vobject/behavior.py", line 152, in serialize
    cls.generateImplicitParameters(obj)
  File "...lib/python2.7/site-packages/vobject/icalendar.py", line 921, in generateImplicitParameters
    obj.add(TimezoneComponent(tzinfo=getTzid(tzid)))
  File "...lib/python2.7/site-packages/vobject/icalendar.py", line 97, in __init__
    self.tzinfo = tzinfo
  File "...lib/python2.7/site-packages/vobject/base.py", line 542, in __setattr__
    prop.fset(self, value)
  File "...lib/python2.7/site-packages/vobject/icalendar.py", line 171, in settzinfo
    transition = getTransition(transitionTo, year, tzinfo)
  File "...lib/python2.7/site-packages/vobject/icalendar.py", line 1878, in getTransition
    uncorrected = firstTransition(generateDates(year, month, day), test)
  File "...lib/python2.7/site-packages/vobject/icalendar.py", line 1836, in firstTransition
    if not test(dt):
  File "...lib/python2.7/site-packages/vobject/icalendar.py", line 1865, in test
    def test(dt): return tzinfo.dst(dt) != zeroDelta
  File "...lib/python2.7/site-packages/pytz/tzinfo.py", line 447, in dst
    dt = self.localize(dt, is_dst)
  File "...lib/python2.7/site-packages/pytz/tzinfo.py", line 327, in localize
    raise NonExistentTimeError(dt)
NonExistentTimeError: 2000-04-02 02:00:00
```

**Comment by medmunds** [comment]
BTW, the code I originally reported [misuses pytz](http://stackoverflow.com/a/26266741/647002) for constructing the datetime. But you get the exact same error using it correctly:

```python
from datetime import datetime
import vobject
import pytz

ical = vobject.iCalendar()
vevent = ical.add('vevent')
vevent.add('dtstart').value = pytz.timezone("America/Los_Angeles").localize(
    datetime(2016, 5, 26, 14, 30))
ical.serialize()  # NonExistentTimeError: 2000-04-02 02:00:00
```

Also, there's already code in vobject.icalendar that tries to [use pytz timezones](https://github.com/eventable/vobject/blob/0.9.2/vobject/icalendar.py#L55-L64) to provide the tzinfo for missing TZIDs, so it seems like vobject *is* meant to work with pytz in at least some cases.
