### ISSUE TITLE
unsupported DTSTART parm: VALUE=DATE-TIME

### ISSUE THREAD

**Issue by PMaynard** [eventable/vobject#36]
Unable to parse ICS file, below, it is a recurring event, generated with android's calendar app. Using vobject version 0.9.2 from pip.

```
cal =`vobject.readOne(data)
```

Trackback 

```
Traceback (most recent call last):
  File "/home/.../main.py", line 17, in <module>
    cal = vobject.readOne(data)
  File "/usr/local/lib/python2.7/dist-packages/vobject/base.py", line 1129, in readOne
    allowQP))
  File "/usr/local/lib/python2.7/dist-packages/vobject/base.py", line 1101, in readComponents
    component.transformChildrenToNative()
  File "/usr/local/lib/python2.7/dist-packages/vobject/base.py", line 660, in transformChildrenToNative
    child = child.transformToNative()
  File "/usr/local/lib/python2.7/dist-packages/vobject/base.py", line 196, in transformToNative
    raise ParseError(msg, lineNumber)
vobject.base.ParseError: "In transformToNative, unhandled exception on line None: <type 'exceptions.ValueError'>: unsupported DTSTART parm: VALUE=DATE-TIME"
```

ICS Source

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//CALENDARSERVER.ORG//NONSGML Version 1//EN
BEGIN:VTIMEZONE
TZID:Europe/London
BEGIN:DAYLIGHT
DTSTART;VALUE=DATE-TIME:20160327T020000
TZNAME:BST
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
END:DAYLIGHT
BEGIN:STANDARD
DTSTART;VALUE=DATE-TIME:20161030T010000
TZNAME:GMT
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:Supervisor Meeting
DTSTART;TZID=Europe/London;VALUE=DATE-TIME:20160623T110000
DTEND;TZID=Europe/London;VALUE=DATE-TIME:20160623T120000
DTSTAMP;VALUE=DATE-TIME:20160621T141052Z
UID:6HJBFNNANM7HBTHEMV1TW52RLFWLTBTV44JN
RRULE:FREQ=WEEKLY
END:VEVENT
END:VCALENDAR
```

**Comment by Pikrass** [comment]
I've got the same problem. The culprit is the dateutil module (rrule.py, _parse_rfc function), which apparently doesn't want to see any parameter at all for DTSTART.

**Comment by wpercy** [comment]
@Pikrass is right, this is a dateutil module error ([source code](https://github.com/dateutil/dateutil/blob/fd466cea181ac2484c35564426263ad51cdd70b1/dateutil/rrule.py#L1491)) - it doesn't want anything passed for DTSTART.

**Comment by cedricpim** [comment]
I am having the same issue. Any suggestions on how to fix it?

**Comment by Unrud** [comment]
https://github.com/dateutil/dateutil/issues/401
