### ISSUE TITLE
Serializing a vcard with base64 encoded picture results in: TypeError: 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by pbiering** [eventable/vobject#46]
While moving to Radicale 2.0.0rc which is turning to use vobject it turned out that serialization of vcards having a picture inside result in:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/vobject/base.py", line 255, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/usr/lib/python3.4/site-packages/vobject/behavior.py", line 162, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/usr/lib/python3.4/site-packages/vobject/base.py", line 993, in defaultSerialize
    child.serialize(outbuf, lineLength, validate=False)
  File "/usr/lib/python3.4/site-packages/vobject/base.py", line 255, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/usr/lib/python3.4/site-packages/vobject/behavior.py", line 162, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/usr/lib/python3.4/site-packages/vobject/base.py", line 1001, in defaultSerialize
    obj.behavior.encode(obj)
  File "/usr/lib/python3.4/site-packages/vobject/vcard.py", line 154, in encode
    line.value = backslashEscape(line.value)
  File "/usr/lib/python3.4/site-packages/vobject/base.py", line 1190, in backslashEscape
    s = s.replace("\\","\\\\").replace(";","\;").replace(",","\,")
TypeError: 'str' does not support the buffer interface
```

vcard contents: 
`
X-MS-CARDPICTURE;TYPE=JPEG;ENCODING=BASE64:/9j/4A...
`
once the line is removed serialization works proper

Used Python version: 3.4

**Comment by pbiering** [comment]
In addition also following error was found on a different encoded photo:

 ```
PHOTO;ENCODING=b;TYPE=JPEG:/9j/4AAQSkZ...
```

```
  File "/opt/pb/bin/radicale-storage-check.py", line 604, in <module>
    item.serialize()
  File "/usr/lib/python3.4/site-packages/vobject/base.py", line 255, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/usr/lib/python3.4/site-packages/vobject/behavior.py", line 162, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/usr/lib/python3.4/site-packages/vobject/base.py", line 993, in defaultSerialize
    child.serialize(outbuf, lineLength, validate=False)
  File "/usr/lib/python3.4/site-packages/vobject/base.py", line 255, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/usr/lib/python3.4/site-packages/vobject/vcard.py", line 227, in serialize
    VCardTextBehavior.serialize(obj, buf, lineLength, validate)
  File "/usr/lib/python3.4/site-packages/vobject/behavior.py", line 162, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/usr/lib/python3.4/site-packages/vobject/base.py", line 1001, in defaultSerialize
    obj.behavior.encode(obj)
  File "/usr/lib/python3.4/site-packages/vobject/vcard.py", line 152, in encode
    line.value = codecs.encode(line.value.encode(coding), "base64").decode("utf-8")
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by wpercy** [comment]
@pbiering can you provide the vcard that threw this error?

**Comment by pbiering** [comment]
Unfortunatly there was no backup of the vcard file. But you should be able to contruct one by using a vcard with a base64 encoded picture inside and simply change the prefix from

`PHOTO;ENCODING=b;TYPE=JPEG:`

to

`X-MS-CARDPICTURE;TYPE=JPEG;ENCODING=BASE64:`

**Comment by pbiering** [comment]
replacing

`X-MS-CARDPICTURE;TYPE=JPEG;ENCODING=BASE64:`

with

`PHOTO;ENCODING=b;TYPE=JPEG:`

will result in passing the vcard.

**Comment by wpercy** [comment]
Yeah, so this is actually because the spec of vCard 3.0 takes `b` as the encoding type for base64, I believe this is intentional. Is that an Outlook exported vCard?
